# Quick Start
#
# 1. run `xhost +local:docker && docker compose up` on the laptop
# 2. open a shell inside a docker container `docker compose exec -it rosbot bash`
# 2. run for e. g. `ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r __ns:=/robot1` inside the container

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:
  rosbot:
    image: husarion/rosbot-gazebo:humble-0.13.1-20240201
    # uncomment to use CPU
    <<: [ *cpu-config]
    # uncomment to use NVIDIA GPU
    # <<: [ *gpu-config]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
      mecanum:=${MECANUM:-False}
      robots:="robot1={y: -4.0}; robot2={y: -2.0}; robot3={y: 4.0};"